"""added path to avatar to user table

Revision ID: 7617fe785036
Revises: f31b163730e6
Create Date: 2018-09-04 14:22:44.700217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7617fe785036'
down_revision = 'f31b163730e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('photo_path', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'photo_path')
    # ### end Alembic commands ###
